### ISSUE TITLE
Roadmap for v0.2.0

### ISSUE THREAD

**Issue by duydang2311** [duydang2311/AltV.Community.MValueAdapters.Generators#6]
## Task list

- [x] Add support for `Guid`, `DateTime`, `DateTimeOffset` types.
- [x] Add support for mutable `record` and `struct` types.
- [x] Remove deprecated `AltExtensions.RegisterAdapters`.
- [x] Add `MValueIgnoreAttribute`.
- [x] Add enum support (#9).
